export type SkillCategory =
  | 'language'
  | 'framework'
  | 'database'
  | 'cloud'
  | 'devops'
  | 'practice';

export type TechnologyCategory =
  | 'frontend'
  | 'backend'
  | 'database'
  | 'cloud'
  | 'devops'
  | 'platform'
  | 'messaging';

export const skills = [
  { id: 'skill-javascript', name: 'JavaScript', category: 'language' },
  { id: 'skill-typescript', name: 'TypeScript', category: 'language' },
  { id: 'skill-html', name: 'HTML', category: 'language' },
  { id: 'skill-css', name: 'CSS', category: 'language' },
  { id: 'skill-python', name: 'Python', category: 'language' },
  { id: 'skill-java', name: 'Java', category: 'language' },
  { id: 'skill-sql', name: 'SQL', category: 'language' },
  { id: 'skill-react', name: 'React', category: 'framework' },
  { id: 'skill-nextjs', name: 'Next.js', category: 'framework' },
  { id: 'skill-tailwind', name: 'Tailwind CSS', category: 'framework' },
  { id: 'skill-nodejs', name: 'Node.js', category: 'framework' },
  { id: 'skill-nestjs', name: 'NestJS', category: 'framework' },
  { id: 'skill-express', name: 'Express.js', category: 'framework' },
  { id: 'skill-fastapi', name: 'FastAPI', category: 'framework' },
  { id: 'skill-spring-boot', name: 'Spring Boot', category: 'framework' },
  { id: 'skill-mongodb', name: 'MongoDB', category: 'database' },
  { id: 'skill-postgresql', name: 'PostgreSQL', category: 'database' },
  { id: 'skill-mysql', name: 'MySQL', category: 'database' },
  { id: 'skill-redis', name: 'Redis', category: 'database' },
  { id: 'skill-aws', name: 'AWS', category: 'cloud' },
  { id: 'skill-docker', name: 'Docker', category: 'devops' },
  { id: 'skill-kubernetes', name: 'Kubernetes', category: 'devops' },
  { id: 'skill-cicd', name: 'CI/CD', category: 'devops' },
  { id: 'skill-linux', name: 'Linux', category: 'devops' },
  { id: 'skill-terraform', name: 'Terraform', category: 'devops' },
  { id: 'skill-git', name: 'Git', category: 'practice' },
  { id: 'skill-github', name: 'GitHub', category: 'practice' },
  { id: 'skill-testing', name: 'Testing', category: 'practice' },
  { id: 'skill-system-design', name: 'System Design', category: 'practice' },
  { id: 'skill-rest', name: 'REST API', category: 'practice' },
] as const satisfies ReadonlyArray<{
  id: string;
  name: string;
  category: SkillCategory;
}>;

export const technologies = [
  { id: 'tech-react', name: 'React', category: 'frontend' },
  { id: 'tech-nextjs', name: 'Next.js', category: 'frontend' },
  { id: 'tech-tailwind', name: 'Tailwind CSS', category: 'frontend' },
  { id: 'tech-nodejs', name: 'Node.js', category: 'backend' },
  { id: 'tech-nestjs', name: 'NestJS', category: 'backend' },
  { id: 'tech-express', name: 'Express.js', category: 'backend' },
  { id: 'tech-python', name: 'Python', category: 'backend' },
  { id: 'tech-fastapi', name: 'FastAPI', category: 'backend' },
  { id: 'tech-java', name: 'Java', category: 'backend' },
  { id: 'tech-spring-boot', name: 'Spring Boot', category: 'backend' },
  { id: 'tech-mongodb', name: 'MongoDB', category: 'database' },
  { id: 'tech-postgresql', name: 'PostgreSQL', category: 'database' },
  { id: 'tech-mysql', name: 'MySQL', category: 'database' },
  { id: 'tech-redis', name: 'Redis', category: 'database' },
  { id: 'tech-docker', name: 'Docker', category: 'devops' },
  { id: 'tech-kubernetes', name: 'Kubernetes', category: 'devops' },
  { id: 'tech-github-actions', name: 'GitHub Actions', category: 'devops' },
  { id: 'tech-aws', name: 'AWS', category: 'cloud' },
  { id: 'tech-vercel', name: 'Vercel', category: 'platform' },
  { id: 'tech-rabbitmq', name: 'RabbitMQ', category: 'messaging' },
] as const satisfies ReadonlyArray<{
  id: string;
  name: string;
  category: TechnologyCategory;
}>;

export const companies = [
  {
    id: 'co-novastack',
    name: 'NovaStack Labs',
    industry: 'SaaS',
    location: 'Bengaluru, India',
    size: 'startup',
  },
  {
    id: 'co-blueorbit',
    name: 'BlueOrbit Technologies',
    industry: 'FinTech',
    location: 'Pune, India',
    size: 'mid',
  },
  {
    id: 'co-cloudforge',
    name: 'CloudForge Systems',
    industry: 'Cloud infrastructure',
    location: 'Hyderabad, India',
    size: 'mid',
  },
  {
    id: 'co-pixelbridge',
    name: 'PixelBridge',
    industry: 'Digital products',
    location: 'Remote',
    size: 'startup',
  },
  {
    id: 'co-datanest',
    name: 'DataNest Solutions',
    industry: 'Data platforms',
    location: 'Mumbai, India',
    size: 'enterprise',
  },
  {
    id: 'co-vertexworks',
    name: 'VertexWorks',
    industry: 'Healthcare software',
    location: 'Chennai, India',
    size: 'mid',
  },
];

export const developers = [
  {
    id: 'dev-priya',
    name: 'Priya Nair',
    email: 'priya.nair@jobmatch.dev',
    title: 'Frontend React Developer',
    experienceYears: 4,
    experienceLevel: 'mid',
    location: 'Bengaluru, India',
  },
  {
    id: 'dev-marcus',
    name: 'Marcus Chen',
    email: 'marcus.chen@jobmatch.dev',
    title: 'MERN Stack Developer',
    experienceYears: 5,
    experienceLevel: 'mid',
    location: 'Austin, USA',
  },
  {
    id: 'dev-aisha',
    name: 'Aisha Rahman',
    email: 'aisha.rahman@jobmatch.dev',
    title: 'NestJS Backend Engineer',
    experienceYears: 6,
    experienceLevel: 'senior',
    location: 'London, UK',
  },
  {
    id: 'dev-liam',
    name: 'Liam OConnor',
    email: 'liam.oconnor@jobmatch.dev',
    title: 'Full-Stack TypeScript Engineer',
    experienceYears: 7,
    experienceLevel: 'senior',
    location: 'Dublin, Ireland',
  },
  {
    id: 'dev-sofia',
    name: 'Sofia Alvarez',
    email: 'sofia.alvarez@jobmatch.dev',
    title: 'Python Backend Developer',
    experienceYears: 3,
    experienceLevel: 'mid',
    location: 'Mexico City, Mexico',
  },
  {
    id: 'dev-kenji',
    name: 'Kenji Tanaka',
    email: 'kenji.tanaka@jobmatch.dev',
    title: 'DevOps Engineer',
    experienceYears: 8,
    experienceLevel: 'senior',
    location: 'Tokyo, Japan',
  },
  {
    id: 'dev-nina',
    name: 'Nina Patel',
    email: 'nina.patel@jobmatch.dev',
    title: 'Next.js Frontend Engineer',
    experienceYears: 2,
    experienceLevel: 'junior',
    location: 'Toronto, Canada',
  },
  {
    id: 'dev-diego',
    name: 'Diego Morales',
    email: 'diego.morales@jobmatch.dev',
    title: 'Java Backend Engineer',
    experienceYears: 9,
    experienceLevel: 'senior',
    location: 'Bogota, Colombia',
  },
];

export const projects = [
  {
    id: 'proj-fintech-dashboard',
    name: 'FinTech Dashboard',
    description:
      'Investor-facing dashboard for portfolio performance, watchlists, and trade activity with accessible charts.',
    domain: 'finance',
  },
  {
    id: 'proj-ecommerce',
    name: 'E-commerce Platform',
    description:
      'Marketplace with product catalog, cart, checkout, and seller inventory APIs.',
    domain: 'retail',
  },
  {
    id: 'proj-banking-api',
    name: 'Banking API Platform',
    description:
      'Account, ledger, and payment APIs with auth, rate limiting, and audit trails.',
    domain: 'finance',
  },
  {
    id: 'proj-saas-analytics',
    name: 'SaaS Analytics Dashboard',
    description:
      'Multi-tenant product analytics with funnels, cohorts, and scheduled reports.',
    domain: 'saas',
  },
  {
    id: 'proj-healthcare',
    name: 'Healthcare Appointment System',
    description:
      'Clinic scheduling, reminders, and provider availability with HIPAA-minded access control.',
    domain: 'healthcare',
  },
  {
    id: 'proj-logistics',
    name: 'Logistics Tracking Platform',
    description:
      'Shipment tracking, warehouse events, and alerting across regional carriers.',
    domain: 'logistics',
  },
  {
    id: 'proj-lms',
    name: 'Learning Management Platform',
    description:
      'Course catalog, progress tracking, and student dashboard for a training startup.',
    domain: 'education',
  },
  {
    id: 'proj-payments',
    name: 'Payments Core Services',
    description:
      'Clearing and settlement services with idempotent payment commands and retry queues.',
    domain: 'finance',
  },
  {
    id: 'proj-collab',
    name: 'Real-time Collaboration App',
    description:
      'Shared documents with presence, comments, and optimistic conflict handling.',
    domain: 'productivity',
  },
  {
    id: 'proj-inventory',
    name: 'Inventory Control Portal',
    description:
      'Warehouse stock levels, purchase orders, and low-stock notifications for retailers.',
    domain: 'logistics',
  },
  {
    id: 'proj-observability',
    name: 'Cloud Observability Stack',
    description:
      'Cluster metrics, log shipping, and deployment health checks for platform teams.',
    domain: 'cloud',
  },
  {
    id: 'proj-clinic-portal',
    name: 'Clinic Admin Portal',
    description:
      'Staff console for patient intake, room assignment, and encounter notes.',
    domain: 'healthcare',
  },
];

export const jobs = [
  {
    id: 'job-react-dev',
    title: 'React Developer',
    description:
      'Build reusable UI for NovaStack’s SaaS console, focusing on React component quality and accessibility.',
    location: 'Bengaluru, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-06-12',
    companyId: 'co-novastack',
  },
  {
    id: 'job-nextjs-dev',
    title: 'Next.js Developer',
    description:
      'Own marketing and app surfaces in Next.js, including routing, data fetching, and Vercel deploys.',
    location: 'Remote',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-06-20',
    companyId: 'co-novastack',
  },
  {
    id: 'job-fullstack-ts',
    title: 'Full Stack TypeScript Engineer',
    description:
      'Ship end-to-end TypeScript features across Next.js clients and NestJS services.',
    location: 'Bengaluru, India',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    status: 'open',
    postedAt: '2026-07-02',
    companyId: 'co-novastack',
  },
  {
    id: 'job-senior-react',
    title: 'Senior React Developer',
    description:
      'Lead frontend architecture for BlueOrbit’s trading console and mentor mid-level engineers.',
    location: 'Pune, India',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    status: 'open',
    postedAt: '2026-05-28',
    companyId: 'co-blueorbit',
  },
  {
    id: 'job-mern',
    title: 'MERN Stack Developer',
    description:
      'Deliver customer-facing flows with React, Express, and MongoDB in a fintech product squad.',
    location: 'Pune, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-07-11',
    companyId: 'co-blueorbit',
  },
  {
    id: 'job-nestjs-backend',
    title: 'NestJS Backend Engineer',
    description:
      'Design payment and ledger APIs in NestJS with PostgreSQL and Redis.',
    location: 'Remote',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    status: 'open',
    postedAt: '2026-06-08',
    companyId: 'co-blueorbit',
  },
  {
    id: 'job-nodejs-backend',
    title: 'Node.js Backend Developer',
    description:
      'Build internal platform APIs in Node.js for CloudForge’s control plane.',
    location: 'Hyderabad, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-07-18',
    companyId: 'co-cloudforge',
  },
  {
    id: 'job-devops',
    title: 'DevOps Engineer',
    description:
      'Operate Kubernetes clusters, CI pipelines, and AWS landing zones for product teams.',
    location: 'Hyderabad, India',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    status: 'open',
    postedAt: '2026-05-19',
    companyId: 'co-cloudforge',
  },
  {
    id: 'job-platform',
    title: 'Platform Engineer',
    description:
      'Bridge frontend delivery and cluster operations — React tooling plus Docker, AWS, and Kubernetes.',
    location: 'Hyderabad, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-07-22',
    companyId: 'co-cloudforge',
  },
  {
    id: 'job-frontend',
    title: 'Frontend Engineer',
    description:
      'Craft PixelBridge marketing and product UI with React and strong HTML/CSS fundamentals.',
    location: 'Remote',
    employmentType: 'contract',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-06-30',
    companyId: 'co-pixelbridge',
  },
  {
    id: 'job-nextjs-junior',
    title: 'Junior Next.js Engineer',
    description:
      'Help ship Next.js pages, Tailwind layouts, and component tests with senior review.',
    location: 'Remote',
    employmentType: 'full-time',
    experienceLevel: 'junior',
    status: 'open',
    postedAt: '2026-07-25',
    companyId: 'co-pixelbridge',
  },
  {
    id: 'job-software-eng',
    title: 'Software Engineer',
    description:
      'Generalist role across APIs and light UI, emphasizing Git discipline and REST design.',
    location: 'Remote',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-06-03',
    companyId: 'co-pixelbridge',
  },
  {
    id: 'job-python-backend',
    title: 'Python Backend Developer',
    description:
      'Implement data-access services in Python with SQL and PostgreSQL for DataNest pipelines.',
    location: 'Mumbai, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-07-04',
    companyId: 'co-datanest',
  },
  {
    id: 'job-java-backend',
    title: 'Java Backend Engineer',
    description:
      'Own Spring Boot services for high-volume ingestion and reporting.',
    location: 'Mumbai, India',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    status: 'open',
    postedAt: '2026-05-14',
    companyId: 'co-datanest',
  },
  {
    id: 'job-data-platform',
    title: 'Data Platform Engineer',
    description:
      'Run Python services on AWS with Dockerized workers and PostgreSQL warehouses.',
    location: 'Mumbai, India',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    status: 'open',
    postedAt: '2026-07-15',
    companyId: 'co-datanest',
  },
  {
    id: 'job-fullstack',
    title: 'Full Stack Engineer',
    description:
      'Deliver clinician-facing features across React UI and Node APIs.',
    location: 'Chennai, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-06-16',
    companyId: 'co-vertexworks',
  },
  {
    id: 'job-healthcare-fe',
    title: 'Healthcare Frontend Engineer',
    description:
      'Build accessible React interfaces for appointment and charting workflows.',
    location: 'Chennai, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-07-08',
    companyId: 'co-vertexworks',
  },
  {
    id: 'job-api-engineer',
    title: 'API Engineer',
    description:
      'Harden NestJS services for clinic integrations with containers and cloud deployment.',
    location: 'Chennai, India',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    status: 'open',
    postedAt: '2026-07-28',
    companyId: 'co-vertexworks',
  },
];

export const hasSkills = [
  // Priya — frontend React (excellent match for React/Next jobs; gap on platform/devops jobs)
  ['dev-priya', 'skill-javascript', 'advanced', 4],
  ['dev-priya', 'skill-typescript', 'advanced', 3],
  ['dev-priya', 'skill-react', 'expert', 4],
  ['dev-priya', 'skill-nextjs', 'advanced', 3],
  ['dev-priya', 'skill-html', 'expert', 4],
  ['dev-priya', 'skill-css', 'advanced', 4],
  ['dev-priya', 'skill-tailwind', 'advanced', 3],
  ['dev-priya', 'skill-git', 'advanced', 4],
  ['dev-priya', 'skill-testing', 'intermediate', 2],
  // Marcus — MERN
  ['dev-marcus', 'skill-javascript', 'advanced', 5],
  ['dev-marcus', 'skill-typescript', 'intermediate', 2],
  ['dev-marcus', 'skill-react', 'advanced', 4],
  ['dev-marcus', 'skill-nodejs', 'advanced', 5],
  ['dev-marcus', 'skill-express', 'advanced', 4],
  ['dev-marcus', 'skill-mongodb', 'advanced', 4],
  ['dev-marcus', 'skill-rest', 'advanced', 5],
  ['dev-marcus', 'skill-git', 'advanced', 5],
  ['dev-marcus', 'skill-docker', 'intermediate', 2],
  // Aisha — NestJS backend
  ['dev-aisha', 'skill-typescript', 'expert', 6],
  ['dev-aisha', 'skill-nodejs', 'expert', 6],
  ['dev-aisha', 'skill-nestjs', 'expert', 5],
  ['dev-aisha', 'skill-rest', 'expert', 6],
  ['dev-aisha', 'skill-postgresql', 'advanced', 5],
  ['dev-aisha', 'skill-redis', 'advanced', 4],
  ['dev-aisha', 'skill-docker', 'advanced', 4],
  ['dev-aisha', 'skill-testing', 'advanced', 5],
  ['dev-aisha', 'skill-system-design', 'advanced', 4],
  // Liam — full-stack TypeScript
  ['dev-liam', 'skill-typescript', 'expert', 7],
  ['dev-liam', 'skill-javascript', 'advanced', 7],
  ['dev-liam', 'skill-react', 'advanced', 5],
  ['dev-liam', 'skill-nextjs', 'advanced', 4],
  ['dev-liam', 'skill-nodejs', 'advanced', 6],
  ['dev-liam', 'skill-nestjs', 'advanced', 4],
  ['dev-liam', 'skill-postgresql', 'advanced', 4],
  ['dev-liam', 'skill-rest', 'advanced', 6],
  ['dev-liam', 'skill-git', 'expert', 7],
  ['dev-liam', 'skill-testing', 'advanced', 5],
  // Sofia — Python backend
  ['dev-sofia', 'skill-python', 'advanced', 3],
  ['dev-sofia', 'skill-fastapi', 'advanced', 3],
  ['dev-sofia', 'skill-rest', 'advanced', 3],
  ['dev-sofia', 'skill-postgresql', 'intermediate', 2],
  ['dev-sofia', 'skill-redis', 'intermediate', 2],
  ['dev-sofia', 'skill-sql', 'advanced', 3],
  ['dev-sofia', 'skill-docker', 'intermediate', 2],
  ['dev-sofia', 'skill-git', 'advanced', 3],
  ['dev-sofia', 'skill-testing', 'intermediate', 2],
  // Kenji — DevOps
  ['dev-kenji', 'skill-aws', 'expert', 7],
  ['dev-kenji', 'skill-docker', 'expert', 8],
  ['dev-kenji', 'skill-kubernetes', 'expert', 6],
  ['dev-kenji', 'skill-cicd', 'expert', 7],
  ['dev-kenji', 'skill-linux', 'advanced', 8],
  ['dev-kenji', 'skill-terraform', 'advanced', 5],
  ['dev-kenji', 'skill-git', 'advanced', 8],
  ['dev-kenji', 'skill-github', 'advanced', 6],
  ['dev-kenji', 'skill-python', 'intermediate', 3],
  // Nina — junior Next.js
  ['dev-nina', 'skill-javascript', 'intermediate', 2],
  ['dev-nina', 'skill-react', 'intermediate', 2],
  ['dev-nina', 'skill-nextjs', 'intermediate', 2],
  ['dev-nina', 'skill-html', 'advanced', 2],
  ['dev-nina', 'skill-css', 'intermediate', 2],
  ['dev-nina', 'skill-tailwind', 'intermediate', 2],
  ['dev-nina', 'skill-git', 'intermediate', 2],
  // Diego — Java backend
  ['dev-diego', 'skill-java', 'expert', 9],
  ['dev-diego', 'skill-spring-boot', 'expert', 8],
  ['dev-diego', 'skill-rest', 'expert', 9],
  ['dev-diego', 'skill-postgresql', 'advanced', 6],
  ['dev-diego', 'skill-mysql', 'advanced', 7],
  ['dev-diego', 'skill-sql', 'expert', 9],
  ['dev-diego', 'skill-docker', 'advanced', 5],
  ['dev-diego', 'skill-system-design', 'expert', 7],
  ['dev-diego', 'skill-testing', 'advanced', 8],
].map(([developerId, skillId, proficiency, years]) => ({
  developerId,
  skillId,
  proficiency,
  years,
}));

export const workedOn = [
  {
    developerId: 'dev-priya',
    projectId: 'proj-fintech-dashboard',
    role: 'Frontend Engineer',
    years: 2,
  },
  {
    developerId: 'dev-marcus',
    projectId: 'proj-ecommerce',
    role: 'Full-Stack Engineer',
    years: 2,
  },
  {
    developerId: 'dev-aisha',
    projectId: 'proj-banking-api',
    role: 'Backend Lead',
    years: 3,
  },
  {
    developerId: 'dev-liam',
    projectId: 'proj-saas-analytics',
    role: 'Full-Stack Engineer',
    years: 2,
  },
  {
    developerId: 'dev-sofia',
    projectId: 'proj-healthcare',
    role: 'Backend Engineer',
    years: 1,
  },
  {
    developerId: 'dev-kenji',
    projectId: 'proj-logistics',
    role: 'Platform Engineer',
    years: 2,
  },
  {
    developerId: 'dev-nina',
    projectId: 'proj-lms',
    role: 'Frontend Engineer',
    years: 1,
  },
  {
    developerId: 'dev-diego',
    projectId: 'proj-payments',
    role: 'Backend Engineer',
    years: 3,
  },
  {
    developerId: 'dev-liam',
    projectId: 'proj-collab',
    role: 'Full-Stack Engineer',
    years: 1,
  },
  {
    developerId: 'dev-marcus',
    projectId: 'proj-inventory',
    role: 'Full-Stack Engineer',
    years: 1,
  },
  {
    developerId: 'dev-kenji',
    projectId: 'proj-observability',
    role: 'DevOps Engineer',
    years: 2,
  },
  {
    developerId: 'dev-sofia',
    projectId: 'proj-clinic-portal',
    role: 'Backend Engineer',
    years: 1,
  },
];

export const projectUses = [
  ['proj-fintech-dashboard', 'tech-react', 'primary'],
  ['proj-fintech-dashboard', 'tech-nextjs', 'primary'],
  ['proj-fintech-dashboard', 'tech-tailwind', 'secondary'],
  ['proj-fintech-dashboard', 'tech-vercel', 'secondary'],
  ['proj-ecommerce', 'tech-react', 'primary'],
  ['proj-ecommerce', 'tech-nodejs', 'primary'],
  ['proj-ecommerce', 'tech-express', 'primary'],
  ['proj-ecommerce', 'tech-mongodb', 'primary'],
  ['proj-ecommerce', 'tech-docker', 'secondary'],
  ['proj-banking-api', 'tech-nestjs', 'primary'],
  ['proj-banking-api', 'tech-nodejs', 'primary'],
  ['proj-banking-api', 'tech-postgresql', 'primary'],
  ['proj-banking-api', 'tech-redis', 'secondary'],
  ['proj-banking-api', 'tech-docker', 'secondary'],
  ['proj-saas-analytics', 'tech-nextjs', 'primary'],
  ['proj-saas-analytics', 'tech-nestjs', 'primary'],
  ['proj-saas-analytics', 'tech-postgresql', 'primary'],
  ['proj-saas-analytics', 'tech-vercel', 'secondary'],
  ['proj-healthcare', 'tech-python', 'primary'],
  ['proj-healthcare', 'tech-fastapi', 'primary'],
  ['proj-healthcare', 'tech-postgresql', 'primary'],
  ['proj-healthcare', 'tech-docker', 'secondary'],
  ['proj-logistics', 'tech-docker', 'primary'],
  ['proj-logistics', 'tech-kubernetes', 'primary'],
  ['proj-logistics', 'tech-aws', 'primary'],
  ['proj-logistics', 'tech-github-actions', 'secondary'],
  ['proj-lms', 'tech-nextjs', 'primary'],
  ['proj-lms', 'tech-react', 'primary'],
  ['proj-lms', 'tech-tailwind', 'secondary'],
  ['proj-lms', 'tech-vercel', 'secondary'],
  ['proj-payments', 'tech-java', 'primary'],
  ['proj-payments', 'tech-spring-boot', 'primary'],
  ['proj-payments', 'tech-mysql', 'primary'],
  ['proj-payments', 'tech-rabbitmq', 'secondary'],
  ['proj-payments', 'tech-docker', 'secondary'],
  ['proj-collab', 'tech-react', 'primary'],
  ['proj-collab', 'tech-nodejs', 'primary'],
  ['proj-collab', 'tech-redis', 'secondary'],
  ['proj-collab', 'tech-rabbitmq', 'secondary'],
  ['proj-inventory', 'tech-react', 'primary'],
  ['proj-inventory', 'tech-mongodb', 'primary'],
  ['proj-inventory', 'tech-nodejs', 'primary'],
  ['proj-inventory', 'tech-docker', 'secondary'],
  ['proj-observability', 'tech-aws', 'primary'],
  ['proj-observability', 'tech-kubernetes', 'primary'],
  ['proj-observability', 'tech-docker', 'primary'],
  ['proj-observability', 'tech-github-actions', 'secondary'],
  ['proj-clinic-portal', 'tech-python', 'primary'],
  ['proj-clinic-portal', 'tech-fastapi', 'primary'],
  ['proj-clinic-portal', 'tech-postgresql', 'primary'],
  ['proj-clinic-portal', 'tech-redis', 'secondary'],
].map(([projectId, technologyId, importance]) => ({
  projectId,
  technologyId,
  importance,
}));

export const requires = [
  // High match: Priya × React Developer
  ['job-react-dev', 'skill-react', true],
  ['job-react-dev', 'skill-javascript', true],
  ['job-react-dev', 'skill-css', true],
  ['job-react-dev', 'skill-typescript', false],
  ['job-react-dev', 'skill-tailwind', false],
  // High match: Priya × Next.js Developer (also Nina junior vs mid)
  ['job-nextjs-dev', 'skill-nextjs', true],
  ['job-nextjs-dev', 'skill-react', true],
  ['job-nextjs-dev', 'skill-typescript', true],
  ['job-nextjs-dev', 'skill-tailwind', false],
  // High match: Liam × Full Stack TypeScript
  ['job-fullstack-ts', 'skill-typescript', true],
  ['job-fullstack-ts', 'skill-react', true],
  ['job-fullstack-ts', 'skill-nodejs', true],
  ['job-fullstack-ts', 'skill-nestjs', true],
  ['job-fullstack-ts', 'skill-postgresql', false],
  // Skill match + poor experience fit: Priya (mid) vs Senior React
  ['job-senior-react', 'skill-react', true],
  ['job-senior-react', 'skill-typescript', true],
  ['job-senior-react', 'skill-javascript', true],
  ['job-senior-react', 'skill-testing', true],
  ['job-senior-react', 'skill-nextjs', false],
  // High match: Marcus × MERN
  ['job-mern', 'skill-react', true],
  ['job-mern', 'skill-nodejs', true],
  ['job-mern', 'skill-mongodb', true],
  ['job-mern', 'skill-express', true],
  ['job-mern', 'skill-docker', false],
  // High match: Aisha × NestJS backend
  ['job-nestjs-backend', 'skill-nestjs', true],
  ['job-nestjs-backend', 'skill-typescript', true],
  ['job-nestjs-backend', 'skill-nodejs', true],
  ['job-nestjs-backend', 'skill-postgresql', true],
  ['job-nestjs-backend', 'skill-redis', false],
  ['job-nestjs-backend', 'skill-docker', false],
  ['job-nodejs-backend', 'skill-nodejs', true],
  ['job-nodejs-backend', 'skill-rest', true],
  ['job-nodejs-backend', 'skill-typescript', true],
  ['job-nodejs-backend', 'skill-express', false],
  ['job-nodejs-backend', 'skill-docker', false],
  // High match: Kenji × DevOps
  ['job-devops', 'skill-aws', true],
  ['job-devops', 'skill-docker', true],
  ['job-devops', 'skill-kubernetes', true],
  ['job-devops', 'skill-cicd', true],
  ['job-devops', 'skill-terraform', false],
  ['job-devops', 'skill-linux', false],
  // Priya skill gap: has React/TS, missing Docker/AWS/Kubernetes; Kenji opposite
  ['job-platform', 'skill-react', true],
  ['job-platform', 'skill-typescript', true],
  ['job-platform', 'skill-docker', true],
  ['job-platform', 'skill-aws', true],
  ['job-platform', 'skill-kubernetes', true],
  ['job-platform', 'skill-cicd', false],
  ['job-frontend', 'skill-javascript', true],
  ['job-frontend', 'skill-html', true],
  ['job-frontend', 'skill-css', true],
  ['job-frontend', 'skill-react', true],
  ['job-frontend', 'skill-nextjs', false],
  // High match: Nina × Junior Next.js
  ['job-nextjs-junior', 'skill-javascript', true],
  ['job-nextjs-junior', 'skill-react', true],
  ['job-nextjs-junior', 'skill-nextjs', true],
  ['job-nextjs-junior', 'skill-tailwind', false],
  ['job-nextjs-junior', 'skill-git', false],
  ['job-software-eng', 'skill-javascript', true],
  ['job-software-eng', 'skill-git', true],
  ['job-software-eng', 'skill-rest', true],
  ['job-software-eng', 'skill-typescript', false],
  ['job-software-eng', 'skill-testing', false],
  // High match: Sofia × Python backend
  ['job-python-backend', 'skill-python', true],
  ['job-python-backend', 'skill-rest', true],
  ['job-python-backend', 'skill-sql', true],
  ['job-python-backend', 'skill-postgresql', true],
  ['job-python-backend', 'skill-fastapi', false],
  ['job-python-backend', 'skill-docker', false],
  // High match: Diego × Java backend
  ['job-java-backend', 'skill-java', true],
  ['job-java-backend', 'skill-spring-boot', true],
  ['job-java-backend', 'skill-rest', true],
  ['job-java-backend', 'skill-sql', true],
  ['job-java-backend', 'skill-docker', false],
  ['job-java-backend', 'skill-system-design', false],
  // Tech overlap / missing skills: Sofia missing AWS; Kenji missing PostgreSQL skill
  ['job-data-platform', 'skill-python', true],
  ['job-data-platform', 'skill-postgresql', true],
  ['job-data-platform', 'skill-aws', true],
  ['job-data-platform', 'skill-docker', true],
  ['job-data-platform', 'skill-kubernetes', false],
  ['job-data-platform', 'skill-terraform', false],
  ['job-fullstack', 'skill-react', true],
  ['job-fullstack', 'skill-nodejs', true],
  ['job-fullstack', 'skill-rest', true],
  ['job-fullstack', 'skill-typescript', true],
  ['job-fullstack', 'skill-postgresql', false],
  ['job-fullstack', 'skill-docker', false],
  ['job-healthcare-fe', 'skill-react', true],
  ['job-healthcare-fe', 'skill-typescript', true],
  ['job-healthcare-fe', 'skill-html', true],
  ['job-healthcare-fe', 'skill-css', true],
  ['job-healthcare-fe', 'skill-nextjs', false],
  ['job-healthcare-fe', 'skill-testing', false],
  // Aisha: NestJS present, AWS/K8s missing — skill gap with NestJS tech overlap
  ['job-api-engineer', 'skill-nestjs', true],
  ['job-api-engineer', 'skill-docker', true],
  ['job-api-engineer', 'skill-aws', true],
  ['job-api-engineer', 'skill-kubernetes', true],
  ['job-api-engineer', 'skill-redis', false],
].map(([jobId, skillId, required]) => ({
  jobId,
  skillId,
  required,
}));

export const jobUses = [
  ['job-react-dev', 'tech-react', 'primary'],
  ['job-react-dev', 'tech-tailwind', 'secondary'],
  ['job-nextjs-dev', 'tech-nextjs', 'primary'],
  ['job-nextjs-dev', 'tech-vercel', 'secondary'],
  ['job-fullstack-ts', 'tech-nextjs', 'primary'],
  ['job-fullstack-ts', 'tech-nestjs', 'primary'],
  ['job-fullstack-ts', 'tech-postgresql', 'secondary'],
  ['job-senior-react', 'tech-react', 'primary'],
  ['job-senior-react', 'tech-nextjs', 'secondary'],
  ['job-mern', 'tech-react', 'primary'],
  ['job-mern', 'tech-nodejs', 'primary'],
  ['job-mern', 'tech-mongodb', 'primary'],
  ['job-nestjs-backend', 'tech-nestjs', 'primary'],
  ['job-nestjs-backend', 'tech-postgresql', 'primary'],
  ['job-nestjs-backend', 'tech-redis', 'secondary'],
  ['job-nodejs-backend', 'tech-nodejs', 'primary'],
  ['job-nodejs-backend', 'tech-express', 'secondary'],
  ['job-devops', 'tech-aws', 'primary'],
  ['job-devops', 'tech-kubernetes', 'primary'],
  ['job-devops', 'tech-docker', 'primary'],
  ['job-devops', 'tech-github-actions', 'secondary'],
  ['job-platform', 'tech-react', 'primary'],
  ['job-platform', 'tech-docker', 'primary'],
  ['job-platform', 'tech-aws', 'primary'],
  ['job-platform', 'tech-kubernetes', 'secondary'],
  ['job-frontend', 'tech-react', 'primary'],
  ['job-frontend', 'tech-tailwind', 'secondary'],
  ['job-nextjs-junior', 'tech-nextjs', 'primary'],
  ['job-nextjs-junior', 'tech-vercel', 'secondary'],
  ['job-software-eng', 'tech-nodejs', 'primary'],
  ['job-software-eng', 'tech-github-actions', 'secondary'],
  ['job-python-backend', 'tech-python', 'primary'],
  ['job-python-backend', 'tech-fastapi', 'primary'],
  ['job-python-backend', 'tech-postgresql', 'secondary'],
  ['job-java-backend', 'tech-java', 'primary'],
  ['job-java-backend', 'tech-spring-boot', 'primary'],
  ['job-java-backend', 'tech-mysql', 'secondary'],
  ['job-data-platform', 'tech-python', 'primary'],
  ['job-data-platform', 'tech-aws', 'primary'],
  ['job-data-platform', 'tech-postgresql', 'primary'],
  ['job-data-platform', 'tech-docker', 'secondary'],
  ['job-fullstack', 'tech-react', 'primary'],
  ['job-fullstack', 'tech-nodejs', 'primary'],
  ['job-fullstack', 'tech-postgresql', 'secondary'],
  ['job-healthcare-fe', 'tech-react', 'primary'],
  ['job-healthcare-fe', 'tech-nextjs', 'secondary'],
  ['job-api-engineer', 'tech-nestjs', 'primary'],
  ['job-api-engineer', 'tech-docker', 'primary'],
  ['job-api-engineer', 'tech-aws', 'secondary'],
].map(([jobId, technologyId, importance]) => ({
  jobId,
  technologyId,
  importance,
}));

export const postedBy = jobs.map((job) => ({
  jobId: job.id,
  companyId: job.companyId,
}));

export const appliedTo = [
  {
    developerId: 'dev-priya',
    jobId: 'job-senior-react',
    appliedAt: '2026-07-30',
    status: 'pending',
  },
  {
    developerId: 'dev-marcus',
    jobId: 'job-mern',
    appliedAt: '2026-08-02',
    status: 'interview',
  },
  {
    developerId: 'dev-aisha',
    jobId: 'job-nestjs-backend',
    appliedAt: '2026-07-21',
    status: 'submitted',
  },
  {
    developerId: 'dev-kenji',
    jobId: 'job-devops',
    appliedAt: '2026-07-09',
    status: 'offer',
  },
  {
    developerId: 'dev-nina',
    jobId: 'job-nextjs-junior',
    appliedAt: '2026-08-05',
    status: 'pending',
  },
];
